### ISSUE TITLE
Feature Request: Team History display

### ISSUE THREAD

**Issue by nhammes** [the-blue-alliance/the-blue-alliance-android#915] opened 2019-04-02 04:44 UTC
When I'm emceeing, I like to pull facts from team history from TBA, but currently the only way to do this in a reasonable amount of time is using a mobile browser. But unfortunately, this is the only reason I need to use a mobile browser to access TBA, because the app is almost always faster on mobile than the browser experience, where they have feature parity.

It would be amazing to have a "History" menu item in the "Select Year" menu, with a display similar to the web versions, like https://www.thebluealliance.com/team/254/history.

**Comment by bherbst** [comment] 2024-12-04 21:40
Closing as duplicate of #216

**Closed by bherbst** 2024-12-04 21:40 UTC
Labels: enhancement
