### ISSUE TITLE
Team historical event data does not always display

### ISSUE THREAD

**Issue by IAmAGitNewbie** [the-blue-alliance/the-blue-alliance-android#396] opened 2015-04-16 01:39 UTC
When I try to view a teams historical events and their records I only see 2015 events:

![screenshot05](https://cloud.githubusercontent.com/assets/2994465/7172474/49d5b92e-e39d-11e4-96f8-16dbda4e115e.png)
(Note that the year at the top is 2013, not 2015)

It happens for any team.  Here are the simple steps to get into this state:

1: Start the TBA app
2: Pull up the menu and select Teams
3: Select any team (I chose Team 1)
4: After the Info tab loads, select the Events tab.  Their 2015 events display
5: Select the first 2015 event and let it load.
6: Press back to get to the Events tab.
7: From the year list at the top select any year (I chose 2013)

The 2015 event data still displays.  No matter what year I pick now (2014, 2011, etc) the events listed will only be for 2015.

I reproduced this on my Galaxy S3 and my Galaxy Tab Pro 12.2 using the TBA 2.1.4.

**Comment by phil-lopreiato** [comment] 2015-04-16 04:35
Yup, I can reproduce. Seems to be an issue when the activity is restored from the back stack. Will investigate...

**Comment by nwalters512** [comment] 2015-04-16 10:47
The first thing that comes to mind is an issue with the event bus but
that's just a suspicion.

**Comment by 1fish2** [comment] 2015-04-18 05:07
This seems to be fixed by 5e8c5f13ae3965f22c4eee56fec2b6cf02c55fd8 . I can reproduce the problem at the previous commit and not with this commit.

**Comment by phil-lopreiato** [comment] 2015-04-18 15:01
Yup, I fixed it in https://github.com/the-blue-alliance/the-blue-alliance-android/commit/5e8c5f13ae3965f22c4eee56fec2b6cf02c55fd8. It'll auto-close once that commit gets merged to master

**Closed** 2015-04-19 21:05 UTC
Labels: bug, in progress, UI
