### ISSUE TITLE
2017 CMP Pit Locations still displaying

### ISSUE THREAD

**Issue by cgmv123** [the-blue-alliance/the-blue-alliance-android#848] opened 2018-02-27 17:06 UTC
![screenshot_20180227-110511](https://user-images.githubusercontent.com/3075725/36742794-3129561e-1bae-11e8-8e2c-ea7e6e48b2b0.png)

Don't think we need to see these anymore.

**Comment by samrmur** [comment] 2018-02-28 00:15
I was able to reproduce this error in the current Android version but not in the latest commit of the _master branch_. It could have been fixed between the two versions (though it may be something else).
<img src="https://user-images.githubusercontent.com/17170253/36762589-5dce09b4-1bf2-11e8-8918-f9d7c8d1d09a.png" width="40%" height="40%">

**Comment by bherbst** [comment] 2024-12-04 21:35
Closing out as obsolete, since we weren't able to reproduce it before and haven't gotten more reports since

**Closed by bherbst** 2024-12-04 21:35 UTC
