### ISSUE TITLE
There's a solid screen in the Back stack

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#807] opened 2017-02-20 22:19 UTC
Steps to reproduce:

1. Upgrade from the current release to today's beta release (4.0.0, 2/20/17 11:44, commit 16424d8).
2. Open the app and proceed to download the data updates.
3. Tap to finish that. IIRC it now shows "2017 Events".
4. Tap the Back button.

Result:
![tba beta is solid](https://cloud.githubusercontent.com/assets/1043120/23143485/9aeae606-f776-11e6-9375-d4569ef84f48.png)

There are no navigational controls here besides the 3 system buttons at the bottom, not even a left side Nav Drawer.

(The first time, I dived into a preseason event and myTBA between steps 3 and 4. I did the shorter sequence above on another Android.)

This is a very minor problem. Tapping the Back button again exits the app. But the Back stack has occasionally done some weird things for a while.

**Comment by phil-lopreiato** [comment] 2017-02-21 16:40
This is odd. That solid screen is the default launch activity (which is implicitly launched and checks if it needs to do the full onboarding). I wonder if this existed pre4.0 as well

**Comment by phil-lopreiato** [comment] 2017-02-21 18:21
@1fish2 I can't reproduce this on my phone, on either my prod build or debug build. Can anyone else get a repro?

**Comment by fangeugene** [comment] 2017-02-21 18:34
I got something similar.

Install old v3.4.8 apk
Go thorough initial download, don't enable myTBA
Update to v4.0.0 through the play store
Tries to download new data, but fails (probably related to #808)
![image](https://cloud.githubusercontent.com/assets/1421884/23179020/795c5e2e-f83a-11e6-92de-520f7b617277.png)

Hitting back results in the blue screen above.
closing the app and reloading it shows:
![image](https://cloud.githubusercontent.com/assets/1421884/23179024/7cb3c9d6-f83a-11e6-9430-aca70f998b47.png)

**Closed** 2017-02-22 17:56 UTC
Labels: bug
