### ISSUE TITLE
Q6 match page shows score BREAKDOWN but not the score RESULTS

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#672] opened 2016-04-07 22:01 UTC
The app was viewing PNCMP match Q6 when the Q6 match-score notification arrived:
![match results but not in the match view](https://cloud.githubusercontent.com/assets/1043120/14368079/61567d2a-fcd0-11e5-8f42-55b9886ccdae.png)

but it didn't change to show the scores, even after tapping the reload button, although it would show the full score breakdown:
![with full breakdown](https://cloud.githubusercontent.com/assets/1043120/14368095/725cb6a2-fcd0-11e5-950e-f0ed0b4fdbda.png)

Going back and forth between tabs, the Breakdown tab shows the score breakdown while the Results tab continues to show only the match time.

18 minutes later, the match-list screen shows scores for Q1 - Q9:
![q1 - q9 have match scores](https://cloud.githubusercontent.com/assets/1043120/14368110/942d23de-fcd0-11e5-9577-d6791aaaa667.png)
and tapping through to Q9 shows scores:
![q9 shows scores](https://cloud.githubusercontent.com/assets/1043120/14368121/a8a72242-fcd0-11e5-956d-b67f654ed976.png)

but tapping through to Q6 still doesn't show scores:
![but q6 still does not show scores](https://cloud.githubusercontent.com/assets/1043120/14368135/c41c8ad0-fcd0-11e5-831f-2e412f9b6021.png)

The event's Ticker shows Q6 results arrived at 14:26 (PT) in the same minute (at least) as the GCM notification arrived:
![event ticker shows results for q6](https://cloud.githubusercontent.com/assets/1043120/14368144/d548c4ae-fcd0-11e5-9cfc-f4d7b2d2299e.png)

Could this be related to #638 being stuck not updating the screen?

**Comment by phil-lopreiato** [comment] 2016-04-07 22:32
Strange, maybe it could be related? 
 
Can you reproduce this with the debug build on newly played matches (to isolate the issue from the notification path)? If so, what does stetho show in the db and what do the API hits return?

**Comment by 1fish2** [comment] 2016-04-07 22:59
I'll try that.

**Comment by 1fish2** [comment] 2016-04-08 00:21
The Firebase "Match result" notification for Q26 arrived at 16:41 (I'm watching that on a tablet) along with GCM notifications for TBA Release builds on 2 phones.

10 minutes later, TBA Release build on one phone is still displaying the Q26 Match screen with match Time instead of scores. It's now displaying the score Breakdown but that took several minutes to arrive.

TBA Debug is still showing no match Results and no Breakdown for Q26, and stetho shows that neither is in the local DB:

> select alliances from matches where key = '2016pncmp_qm26'
> {"blue":{"score":-1,"teams":["frc5803","frc4089","frc1258"]},"red":{"score":-1,"teams":["frc4132","frc2635","frc955"]}}
> select breakdown from matches where key = '2016pncmp_qm26'
> [nothing]

On TBA Release, navigating back to the Matches list showed Q26 scores, and navigating forwards to Q26 flashed the scores briefly then replaced them with the Time (like the #638 symptom).

On TBA Debug, navigating back to the Matches list showed the Q26 and Q27 scores after a fraction of a second delay (presumably after fetching the API data) but stetho still shows no scores or breakdowns for Q26 in the `matches` table, and navigating forwards to the Q26 screen still shows the Time and no Breakdown. Tapping the "refresh" button on the Breakdown tab makes the icon and "No match breakdown found" label disappear without showing the data. 

The event Ticker does show Q26 scores on TBA Debug. Navigating through to the Q26 Match screen still shows the Time. Sometimes tapping the "refresh" button makes it flash the scores briefly.

At 17:10 finally navigating from the Ticker to the Q26 screen on TBA Debug shows the scores and Breakdown, and stetho shows that they're in the local DB *but* navigating from the Matches list (which shows Q26 scores) to the Q26 screen still doesn't show either! The refresh button doesn't help that.

At 17:16 the latter sequence on TBA Debug shows the Breakdown but no scores.

On TBA Release, the PNCMP Ticker was empty even with nothing filtered out. Changing the filter didn't help. The refresh button didn't help. After navigating to the week's Events and back, it works. Could this be another symptom of a stuck empty screen?

**Comment by 1fish2** [comment] 2016-04-08 00:26
Shortly afterwards, I woke the tablet to see its Ticker also "No items match the applied filter". Again, navigating to the Events list and back fixed it.

**Comment by nwalters512** [comment] 2016-04-08 00:33
I can't speak for the rest of the issues (that's very weird behavior), but the ticker is completely unrelated, that's all done with Firebase. Can you check logcat for any Firebase errors?

**Comment by 1fish2** [comment] 2016-04-08 00:38
(OK. I'll check logcat in a minute.)

For Q33, TBA Debug Q33 screen will now flash up the match scores and then revert to the Time, and it'll show the Breakdown. Stetho showns neither of those in the local DB. Navigating to the Match list (which shows Q33 scores) and back, Results shows the Time and Breakdown is back to "No match breakdown found".

**Comment by phil-lopreiato** [comment] 2016-04-08 00:41
Weird... Thanks so much for the thorough investigating you're doing!

I have one more question for next time you see it. Using stetho in the debug build, you should be able to see the network calls - what are the endpoints for event matches and single match info returning?
* * *
- So it looks like updating information isn't making it into the database. I've seen at rare times logcat being flooded with data about the database thread pool being full, and new writes not being able to occur (something like that, I'm going off memory and can't find the it on StackOverflow at the moment). The match list uses [MatchListWriter](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/database/writers/MatchListWriter.java#L21) and a single match uses [MatchWriter](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/database/writers/MatchWriter.java#L18) (both of which call into [ModelTable](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/database/ModelTable.java#L38) to do the actual writes). 
- Data is inserted into a list from [ListViewBinder](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/binders/ListViewBinder.java#L33) (both the match list and a match score use this, the breakdown uses [MatchBreakdownBinder](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/binders/MatchBreakdownBinder.java)). The binders contain the logic of whether or not to show the `NoDataView` or not. 

Can you try and maybe set some breakpoints in some of the classes I mentioned and see what's actually going on?

I'll work with you tomorrow debugging further, we can coordinate on slack

**Comment by 1fish2** [comment] 2016-04-08 00:45
@nwalters512 indeed, there are 8 Firebase errors in the logcat. I'll file a separate Issue.

**Comment by 1fish2** [comment] 2016-04-08 01:34
**Looking through logcat for clues**

* The Release build on the same phone received Q26 match breakdown results at 16:41:08, which is right after the match score GCM arrived and long before the Debug build would display the score Breakdown. I wasn't viewing the release build on that phone. Is it expected that it'd fetch and log the breakdown?

```
04-07 16:41:08.092  6322 11730 I tba-android: Received : (match_score)  {"match":{"score_breakdown":{"red":{"foulCount":0,"position4crossings":2,"position1crossings":2,"capturePoints":0,"teleopChallengePoints":15,"teleopCrossingPoints":25,"autoBoulderPoints":0,"position3crossings":2,"towerEndStrength":-3,"robot3Auto":"Crossed","autoBouldersLow":0,"techFoulCount":0,"autoCrossingPoints":30,"foulPoints":0,"position2":"A_ChevalDeFrise","position3":"D_RockWall","position4":"B_Ramparts","teleopPoints":58,"position5":"C_SallyPort","robot2Auto":"Crossed","teleopDefensesBreached":true,"teleopTowerCaptured":false,"adjustPoints":0,"autoPoints":30,"teleopBouldersLow":4,"teleopBouldersHigh":2,"position5crossings":0,"towerFaceC":"Challenged","totalPoints":88,"teleopBoulderPoints":18,"towerFaceB":"Challenged","breachPoints":0,"position2crossings":2,"autoReachPoints":0,"autoBouldersHigh":0,"teleopScalePoints":0,"robot1Auto":"Crossed","towerFaceA":"Challenged"},"blue":{"foulCount":0,"position4crossings":2,"position1crossings":2,"capturePoints":0,"teleopChallengePoints":5,"teleopCrossingPoints":35,"autoBoulderPoints":0,"position3crossings":2,"towerEndStrength":2,"robot3Auto":"Crossed","autoBouldersLow":0,"techFoulCount":0,"autoCrossingPoints":30,"foulPoints":0,"position2":"C_SallyPort","position3":"D_RockWall","position4":"B_Moat","teleopPoints":77,"position5":"A_ChevalDeFrise","robot2Auto":"Crossed","teleopDefensesBreached":true,"teleopTowerCaptured":false,"adjustPoints":0,"autoPoints":30,"teleopBouldersLow":11,"teleopBouldersHigh":0,"position5crossings":2,"towerFaceC":"None","totalPoints":107,"teleopBoulderPoints":22,"towerFaceB":"Scaled","breachPoints":0,"position2crossings":2,"autoReachPoints":0,"autoBouldersHigh":0,"teleopScalePoints":15,"robot1Auto":"Crossed","towerFaceA":"Challenged"}},"set_number":1,"alliances":{"red":{"score":88,"teams":["frc4132","frc2635","frc955"]},"blue":{"score":107,"teams":["frc5803","frc4089","frc1258"]}},"videos":[],"time":1460071860,"time_string":null,"comp_level":"qm","key":"2016pncmp_qm26","event_key":"2016pncmp","match_number":26},"event_name":"Pacific Northwest District Championship sponsored by Autodesk","event_key":"2016pncmp"}
```

* There are 16 log messages like these:

```
04-07 17:17:32.143 8179-8179/com.thebluealliance.androidclient.development D/tba-android: UNBINDING
04-07 17:17:32.144 8179-8179/com.thebluealliance.androidclient.development W/GAv4: Discarding hit. Missing tracking id parameter: a=1402828662,an=The Blue Alliance Debug,t=event,cd=com.thebluealliance.androidclient.activities.ViewEventActivity,sf=100.0,ec=refresh,tid=,ea=toolbar-button,aid=3.2.1-27+g41e8fba,el=eventAlliances_2016pncmp,av=3.2.1-27+g41e8fba
04-07 17:17:32.146 8179-31524/com.thebluealliance.androidclient.development D/tba-android: FETCHING https://www.thebluealliance.com/api/v2/event/2016pncmp
```

* Two occurrences of this stack trace pair:

```
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development E/tba-android: UNABLE TO RENDER
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.binders.StatsListBinder.setSelectedList(StatsListBinder.java:78)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.binders.StatsListBinder.updateData(StatsListBinder.java:37)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.binders.StatsListBinder.updateData(StatsListBinder.java:20)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.lambda$bindData$21(BaseAPISubscriber.java:170)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.access$lambda$2(BaseAPISubscriber.java)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber$$Lambda$3.call(Unknown Source)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-07 17:17:32.776 8179-8179/com.thebluealliance.androidclient.development W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-07 17:17:32.777 8179-8179/com.thebluealliance.androidclient.development E/tba-android: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
                                                                                              at com.thebluealliance.androidclient.binders.StatsListBinder.setSelectedList(StatsListBinder.java:78)
                                                                                              at com.thebluealliance.androidclient.binders.StatsListBinder.updateData(StatsListBinder.java:37)
                                                                                              at com.thebluealliance.androidclient.binders.StatsListBinder.updateData(StatsListBinder.java:20)
                                                                                              at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.lambda$bindData$21(BaseAPISubscriber.java:170)
                                                                                              at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.access$lambda$2(BaseAPISubscriber.java)
                                                                                              at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber$$Lambda$3.call(Unknown Source)
                                                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

* 16 of these SQL errors:

```
04-07 17:20:05.941 8179-8786/com.thebluealliance.androidclient.development E/SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=PERSIST] 
04-07 17:20:05.942 8179-8786/com.thebluealliance.androidclient.development W/SQLiteConnection: Could not change the database journal mode of '/data/user/0/com.thebluealliance.androidclient.development/databases/the-blue-alliance-android-database' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.
```

**Comment by phil-lopreiato** [comment] 2016-04-08 02:17
> Is it expected that it'd fetch and log the breakdown?

Yes, we log the data of incoming gcm messages

> NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)

Not related to this, but a bug we should fix anyway. 

> Could not change the database journal mode

I haven't seen this before, but it looks promising...

**Comment by 1fish2** [comment] 2016-04-08 02:18
Oops! I was wrong about not viewing the Release build on that phone. I probably tapped on a notification (perhaps the Q26 "Match result" notification) which would've opened the Release build, and didn't notice the red/blue thing.

That could be why trying to view the match results didn't change the local DB.

**Comment by 1fish2** [comment] 2016-04-08 17:24
Monitoring the sequence for SVR Q4 in the Debug app (not GCM enabled):

1. Navigate from the Matches screen to the Q4 screen.
2. Wait for scores to be posted. ... They appeared in another phone's Firebase ticker.
3. The "refresh" button on the Q4 screen doesn’t show match scores (!).
4. The Breakdown tab is empty (and missing the icon & label) (!).
5. Refresh fetched data from https://www.thebluealliance.com/api/v2/match/2016casj_qm4 twice (!) and received `null` breakdown and `-1` scores (!).
6. Navigate back to Matches screen fetched lots of data and displayed Q4 results, but they did not get into the local DB's `matches` table (!).
7. Navigate back to Q4 screen. It made no network requests (!). It still shows no scores (!). It shows Breakdown with the icon and no-data label. (Showing the icon and no-data label vs. plain white is intermittent (!).)
8. The "refresh" button fetched `match/2016casj_qm4` twice again and received match scores and breakdown. It’s now in the `matches` table but the Q4 screen still doesn’t show scores or breakdown (!).
9. Some time later, Q6 scores are on TBA web site. The Q4 screen still shows no scores or breakdown. The "refresh" button again fetched `match/2016casj_qm4`, got scores & breakdown, but the screen still doesn't show either (!).
10. Yet later, Q8 scores are on TBA web site. The "refresh" button again fetched `match/2016casj_qm4`, received `-1` scores and `null` breakdown this time (!!), and the Q4 screen flashed the scores then went back to showing the match Time (!). The Q4 Breakdown tab has white contents.

The app's logcat has some of these errors:

> 04-08 09:45:49.829 8179-31708/com.thebluealliance.androidclient.development E/SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=PERSIST] 
> 04-08 09:45:49.830 8179-31708/com.thebluealliance.androidclient.development W/SQLiteConnection: Could not change the database journal mode of '/data/user/0/com.thebluealliance.androidclient.development/databases/the-blue-alliance-android-database' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.

Phil says the `Could not change the database journal mode` warning might be due to a [stetho side effect](https://github.com/facebook/stetho/issues/84).

Sometimes the app sent https://www.thebluealliance.com/api/v2/event/2016casj/matches and got a 304 not modified response.

There was a short time where the web site's [SVR Q2 match page](http://www.thebluealliance.com/match/2016casj_qm2) was not yet showing results for while the [SVR Matches tab](http://www.thebluealliance.com/event/2016casj) was showing results.

**Comment by phil-lopreiato** [comment] 2017-02-20 04:04
This should be fixed now that we track last modified times (see #788), so these issues are _hopefully_ fixed. We can revisit if that proves not to be the case. Thanks for all your hard work debugging, @1fish2!

**Closed by phil-lopreiato** 2017-02-20 04:04 UTC
