### ISSUE TITLE
Fix team year selection

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#440] opened 2015-08-05 04:53 UTC
On the branch with the new datafeed implementation, the ability to select a team year to view historical data is broken. This should be fixed before this is released to prod.

**Comment by Adam8234** [comment] 2015-10-04 14:47
Is this pushed to prod yet? With the current version on the Google Play Store, the team year selection doesn't work. Doesn't even display the current selected.

**Comment by phil-lopreiato** [comment] 2015-10-05 03:22
I can't reproduce that on the current Play Store build, but it's probably a known issue where the database locks up and the loading spins for a long time. 

All those issues should be fixed on the rebuild branch, which should go out to beta in the next week or so

**Comment by Adam8234** [comment] 2015-10-05 03:25
Yep. I did forget that the rewrite is almost done. Good to know I guess. I completely forgot how it ended up that way, but I'd assume by just clearing the data would be a temporary fix for the current v2 version. Thanks Phil

**Comment by phil-lopreiato** [comment] 2015-10-05 03:28
Usually even closing and reopening the app fixes the lock issues. We never really traced down the cause and it's not an issue with the new data feed because it's done much better now. So we just kinda let it be

**Comment by Adam8234** [comment] 2015-10-05 03:36
Even by closing the app, it didn't fix it. I just ended up clearing the data and setting it back up again. But if it's already fixed, that's great! Good job everyone.

**Comment by phil-lopreiato** [comment] 2015-10-05 03:38
Thanks! The db locks were a big thorn in our side for a while, and something we definitely tried to architect to avoid on the new data feed. Fingers crossed it works...

**Closed** 2015-10-12 19:21 UTC
Labels: next-release
