### ISSUE TITLE
2019 Score Breakdown clips on smaller screens

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-android#902] opened 2019-03-03 15:30 UTC
![screenshot_20190302-180239](https://user-images.githubusercontent.com/57101/53697469-6380f180-3d9f-11e9-9459-7eb9e4e6c4bc.jpg)

**Comment by bherbst** [comment] 2024-12-04 21:33
Duplicate of #898

**Closed by bherbst** 2024-12-04 21:33 UTC
Labels: bug, duplicate
